version: "2"

services:

  server:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - 80:80

  postgres:
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
