version: "3"
services:
  server:
    image: node:alpine
    volumes:
      - .:/app:cached
    ports:
      - 80:80
      - 443:443
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev"
  postgres:
    image: postgres:alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
