version: "3"
services:
  server:
    image: node:latest
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:80
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev"
