on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            git clone https://github.com/fadeev/ibcgraph ; \
            cd ibcgraph ; \
            git pull origin master ; \
            docker stop $$(docker ps -q --filter ancestor=ibcgraph) ; \
            docker build -t ibcgraph . ; \
            docker run -d -p 80:80 ibcgraph ; \
