on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/ibc-viz-server
            git pull
            docker-compose -f docker-compose.yml -f prod.yaml down
            sudo rm -rf postgres-data
            docker-compose -f docker-compose.yml -f prod.yaml up -d
