on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            git clone https://github.com/fadeev/ibcgraph ; \
            cp key ibcgraph/ ; \
            cp cert ibcgraph/ ; \
            cd ibcgraph ; \
            git pull origin master ; \
            rm -rf postgres-data ; \
            docker-compose down ; \
            docker-compose up -d
